
server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
      - id: customer-service
        uri: 
          lb://customer-service
        predicates:
        - Path=/customers/**        
      - id: address-service
        uri: 
          lb://address-service
        predicates:
        - Path=/addresses/**
        